---
- name: Deploy our Database (MySql)
  hosts: "{{host}}"
  roles:
      - Database


- name: Deploy our Webserver
  hosts: "{{host}}"
  roles:
      - Webserver

- name: Deploy our NTP server
  hosts: "{{host}}"
  roles:
      - NTP
