---
# tasks file for NTP_Client
      - name: Update our instance
        apt:  
          name: "*"
          state: latest
          update_cache: yes

      - name: Install NTP Server
        apt:
          name: ntp
          state: latest     

      - name: Add our ntp server in ntp.conf
        ansible.builtin.lineinfile:
          path: /etc/ntpsec/ntp.conf
          line: 'server 54.226.103.95 prefer iburst'
          insertafter: EOF
      
      - name: Start NTP Server
        ansible.builtin.service:
          enabled: yes
          name: ntp 
          state: started

      - name: Confirm the changes
        action: 
          command ntpq -p
